// File generated by FlutterFire CLI.
// Run `dart run flutterfire_cli:flutterfire configure` to regenerate with your
// Firebase project configuration. Do not commit API keys to version control.
//
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// **IMPORTANT**: Run `dart run flutterfire_cli:flutterfire configure` to
/// replace this placeholder with your actual Firebase project config.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoo64tsSA-MpUEHDevfH_jUJcAvxJwRsE',
    appId: '1:843252671350:web:89b21384cc6992f9209057',
    messagingSenderId: '843252671350',
    projectId: 'rolekeeper-7ddcc',
    authDomain: 'rolekeeper-7ddcc.firebaseapp.com',
    storageBucket: 'rolekeeper-7ddcc.firebasestorage.app',
    measurementId: 'G-GM43ZSH86Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBku_Qn6fTvCyxpDCglOR1gcKHP8RntWhk',
    appId: '1:843252671350:android:d8c434e7296c81ce209057',
    messagingSenderId: '843252671350',
    projectId: 'rolekeeper-7ddcc',
    storageBucket: 'rolekeeper-7ddcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHmPtsFP1S5C4Lh-8LVZX85c07asbp0qM',
    appId: '1:843252671350:ios:66e9e8fa1ddbab37209057',
    messagingSenderId: '843252671350',
    projectId: 'rolekeeper-7ddcc',
    storageBucket: 'rolekeeper-7ddcc.firebasestorage.app',
    iosBundleId: 'com.rolekeeper.rolekeeper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHmPtsFP1S5C4Lh-8LVZX85c07asbp0qM',
    appId: '1:843252671350:ios:66e9e8fa1ddbab37209057',
    messagingSenderId: '843252671350',
    projectId: 'rolekeeper-7ddcc',
    storageBucket: 'rolekeeper-7ddcc.firebasestorage.app',
    iosBundleId: 'com.rolekeeper.rolekeeper',
  );

}